<ADSWorkspace Revision="28" Version="100">
    <Workspace Name="">
        <LibraryDefs Name="lib.defs" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Preferences Name="layout.prf" />
        <Preferences Name="schematic.prf" />
        <Library Name="ads_standard_layers" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_builtin" />
        <Library Name="ads_standard_layers_ic" />
        <Library Name="ads_schematic_layers_ic" />
        <Library Name="ads_schematic_ports_ic" />
        <Library Name="ads_rflib" />
        <Library Name="ads_sources" />
        <Library Name="ads_simulation" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_datacmps" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_pelib" />
        <Library Name="ads_serdes_ref_channel" />
        <Library Name="ads_quantum" />
        <Library Name="Simulation_Sequencing" />
        <Library Name="RFBOARDV2_lib" />
        <Cell Name="RFBOARDV2_lib:1.6 GHz Matching Networks" />
        <Log Name="search_history.log" />
        <Log Name="netlist.log" />
        <Dataset Name="antennapluscoaxialcable.ds" />
        <Data_Files Name="antennapluscoaxialcable.ds" />
        <Data_Files Name="antennapluscoaxialcable_data\logFile.txt" />
        <ConfigFile Name="dds.cfg" />
        <Cell Name="RFBOARDV2_lib:antennapluscoaxialcablemeasured" />
        <ConfigFile Name="linecalc.cfg" />
        <Data_Display Name="1.2 GHz matching network.dds" />
        <Data_Display Name="1.2 GHz Matching With Filter.dds" />
        <Data_Display Name="1.42 GHz matching network.dds" />
        <Data_Display Name="1.42 Matching With Filter.dds" />
        <Data_Display Name="1.6 GHz Matching Networks.dds" />
        <Data_Display Name="1.6 GHz Matching With Filter.dds" />
        <Data_Display Name="antennapluscoaxialcablemeasured.dds" />
        <Data_Display Name="antennapluscoaxialcablemeasuredportextensionincludedinmeasurements.dds" />
        <Data_Display Name="antennaplustwoinchcableNOVNACABLE.dds" />
        <Data_Display Name="HFSSSimulatedAntenna.dds" />
        <Data_Display Name="simulatedantennapluscoaxialcable.dds" />
        <Preferences Name="ads_datacmps_lay.prf" />
        <Preferences Name="RFBOARDV2_lib_lay.prf" />
        <Dataset Name="_1.2_GHz_matching_network.ds" />
        <Dataset Name="_1.2_GHz_Matching_With_Filter.ds" />
        <Dataset Name="_1.42_GHz_matching_network.ds" />
        <Dataset Name="_1.42_Matching_With_Filter.ds" />
        <Dataset Name="_1.6_GHz_Matching_Networks.ds" />
        <Dataset Name="_1.6_GHz_Matching_With_Filter.ds" />
        <Dataset Name="AntennaByItself.ds" />
        <Dataset Name="antennapluscoaxialcablemeasured.ds" />
        <Dataset Name="antennapluscoaxialcablemeasuredportextensionincludedinmeasurements.ds" />
        <Dataset Name="antennaplustwoinchcableNOVNACABLE.ds" />
        <Dataset Name="HFSSSimulatedAntenna.ds" />
        <Dataset Name="simulatedantennapluscoaxialcable.ds" />
        <Data_Files Name="AntennaByItself.ds" />
        <Data_Files Name="AntennaByItself_data\logFile.txt" />
        <Data_Files Name="antennapluscoaxialcablemeasured.ds" />
        <Data_Files Name="antennapluscoaxialcablemeasuredportextensionincludedinmeasurements.ds" />
        <Data_Files Name="antennapluscoaxialcablemeasuredportextensionincludedinmeasurements_data\logFile.txt" />
        <Data_Files Name="antennapluscoaxialcablemeasured_data\logFile.txt" />
        <Data_Files Name="antennaplustwoinchcableNOVNACABLE.ds" />
        <Data_Files Name="antennaplustwoinchcableNOVNACABLE_data\logFile.txt" />
        <Data_Files Name="HFSSSimulatedAntenna.ds" />
        <Data_Files Name="HFSSSimulatedAntenna_data\logFile.txt" />
        <Data_Files Name="simulatedantennapluscoaxialcable.ds" />
        <Data_Files Name="simulatedantennapluscoaxialcable_data\logFile.txt" />
        <Data_Files Name="_1.2_GHz_matching_network.ds" />
        <Data_Files Name="_1.2_GHz_matching_network_data\logFile.txt" />
        <Data_Files Name="_1.2_GHz_Matching_With_Filter.ds" />
        <Data_Files Name="_1.2_GHz_Matching_With_Filter_data\logFile.txt" />
        <Data_Files Name="_1.42_GHz_matching_network.ds" />
        <Data_Files Name="_1.42_GHz_matching_network_data\logFile.txt" />
        <Data_Files Name="_1.42_Matching_With_Filter.ds" />
        <Data_Files Name="_1.42_Matching_With_Filter_data\logFile.txt" />
        <Data_Files Name="_1.6_GHz_Matching_Networks.ds" />
        <Data_Files Name="_1.6_GHz_Matching_Networks_data\logFile.txt" />
        <Data_Files Name="_1.6_GHz_Matching_Networks_data\spare_removal.txt" />
        <Data_Files Name="_1.6_GHz_Matching_With_Filter.ds" />
        <Data_Files Name="_1.6_GHz_Matching_With_Filter_data\logFile.txt" />
        <Cell Name="RFBOARDV2_lib:1.2 GHz Matching With Filter" />
        <Cell Name="RFBOARDV2_lib:1.2 GHz matching network" />
        <Cell Name="RFBOARDV2_lib:1.42 GHz matching network" />
        <Cell Name="RFBOARDV2_lib:1.42 Matching With Filter" />
        <Cell Name="RFBOARDV2_lib:1.6 GHz Matching With Filter" />
        <Cell Name="RFBOARDV2_lib:AntennaByItself" />
        <Cell Name="RFBOARDV2_lib:HFSSSimulatedAntenna" />
        <Cell Name="RFBOARDV2_lib:antennapluscoaxialcablemeasuredportextensionincludedinmeasurements" />
        <Cell Name="RFBOARDV2_lib:antennaplustwoinchcableNOVNACABLE" />
        <Cell Name="RFBOARDV2_lib:simulatedantennapluscoaxialcable" />
        <Cell Name="RFBOARDV2_lib:coaxialcablebyitselfmeasurement" />
        <Dataset Name="coaxialcablebyitselfmeasurement.ds" />
        <Data_Files Name="coaxialcablebyitselfmeasurement.ds" />
        <Data_Files Name="coaxialcablebyitselfmeasurement_data\logFile.txt" />
        <Data_Display Name="coaxialcablebyitselfmeasurement.dds" />
        <Dataset Name="coaxialbyitselfnoportextension.ds" />
        <Data_Files Name="coaxialbyitselfnoportextension.ds" />
        <Dataset Name="Twocables2adaptersNOPort.ds" />
        <Data_Files Name="Twocables2adaptersNOPort.ds" />
        <Dataset Name="coaxialcablethruadapterwith18psintoport2.ds" />
        <Data_Files Name="coaxialcablethruadapterwith18psintoport2.ds" />
        <Cell Name="RFBOARDV2_lib:RF Switch" />
        <Log Name="readgbr.log" />
        <Log Name="brd_reader.log" />
        <Cell Name="RFBOARDV2_lib:DistribFilter" />
        <Cell Name="RFBOARDV2_lib:1" />
        <Log Name="writegbr.log" />
        <Log Name="writedxf.log" />
        <Dataset Name="RF_Switch.ds" />
        <Data_Files Name="RF_Switch.ds" />
        <Data_Files Name="RF_Switch_data\logFile.txt" />
        <Data_Display Name="RF Switch.dds" />
        <Data_Files Name="RF_Switch_data\spare_removal.txt" />
        <Cell Name="RFBOARDV2_lib:automatchtest" />
        <Dataset Name="SA_TaperedLineMatch1_automatchtest.ds" />
        <Data_Files Name="SA_TaperedLineMatch1_automatchtest.ds" />
        <Data_Files Name="SA_TaperedLineMatch1_automatchtest_data\logFile.txt" />
        <Dataset Name="automatchtest.ds" />
        <Data_Files Name="automatchtest.ds" />
        <Data_Files Name="automatchtest_data\logFile.txt" />
        <Data_Display Name="automatchtest.dds" />
        <Cell Name="RFBOARDV2_lib:BroadbandmatchingNetwork" />
        <Dataset Name="BroadbandmatchingNetwork.ds" />
        <Data_Files Name="BroadbandmatchingNetwork.ds" />
        <Data_Files Name="BroadbandmatchingNetwork_data\logFile.txt" />
        <Data_Display Name="BroadbandmatchingNetwork.dds" />
        <Log Name="readdxf.log" />
        <Layer_Preference Name="ads_standard_layers.layerprf" />
        <Preferences Name="ads_rflib_lay.prf" />
        <Preferences Name="ads_tlines_lay.prf" />
        <Preferences Name="RFBOARDV2_lib_sch.prf" />
        <Preferences Name="RFSWITCHBOARDINCHES_lay.prf" />
        <Preferences Name="RFSWITCHBOARDINCHES_sch.prf" />
        <Data_Files Name="_1.6_GHz_Matching_With_Filter_data\spare_removal.txt" />
        <Library Name="RFSWITCHBOARDINCHES" />
        <Cell Name="RFSWITCHBOARDINCHES:QFN12_SKY" />
        <Cell Name="RFSWITCHBOARDINCHES:QFN12_SKY_1" />
        <Cell Name="RFBOARDV2_lib:tracewidthsbeingthesame" />
        <Dataset Name="tracewidthsbeingthesame.ds" />
        <Data_Files Name="tracewidthsbeingthesame.ds" />
        <Data_Files Name="tracewidthsbeingthesame_data\logFile.txt" />
        <Data_Display Name="tracewidthsbeingthesame.dds" />
        <Data_Display Name="tracewidithV2.dds" />
        <Dataset Name="__simdata019846.ds" />
        <Dataset Name="__simdata027558.ds" />
        <Dataset Name="tracewidithV2.ds" />
        <Data_Files Name="tracewidithV2.ds" />
        <Data_Files Name="tracewidithV2_data\logFile.txt" />
        <Data_Files Name="__simdata019846.ds" />
        <Data_Files Name="__simdata027558.ds" />
        <Cell Name="RFSWITCHBOARDINCHES:tracewidithV2" />
        <Data_Files Name="tracewidithV2_data\spare_removal.txt" />
        <Layer_Preference Name="RFSWITCHBOARDINCHES.layerprf" />
        <Layer_Preference Name="ads_schematic_layers.layerprf" />
        <Cell Name="RFBOARDV2_lib:tracewidthV3" />
    </Workspace>
</ADSWorkspace>
